name: Request for Additional blog
description: "Create a request to add a blog to the feed."
title: "[Add]: "
labels: ["add request"]

body:
- type: input
  id: blog-title
  attributes:
    label: "Blog title"
    placeholder: AWESOME BLOG
  validations:
    required: true
- type: input
  id: blog-url
  attributes:
    label: "Blog URL"
    placeholder: https://blog.example.com
  validations:
    required: true
- type: input
  id: blog-feed-url
  attributes:
    label: "Blog feed URL (if possible)"
    placeholder: https://blog.example.com/feed
  validations:
    required: true
- type: checkboxes
  id: checkboxes-1
  attributes:
    label: Checkboxes
    options:
      - label: I've confirmed that there are no duplicates here.
        required: true