name: ブログの追加要望
description: "アンテナにブログを追加する要望を作成します"
title: "[Add]: <ここにブログ名を入力>"
labels: ["add request"]

body:
- type: input
  id: blog-title
  attributes:
    label: "ブログのタイトル"
    placeholder: 〇〇ブログ
  validations:
    required: true
- type: input
  id: blog-url
  attributes:
    label: "ブログのURL"
    placeholder: https://blog.example.com
  validations:
    required: true
- type: input
  id: blog-feed-url
  attributes:
    label: "ブログのRSSフィードのURL (可能であれば)"
    placeholder: https://blog.example.com/feed
- type: markdown
  attributes:
    value: |
      ## 確認してください
      追加リクエストありがとうございます！最後に、[この](https://github.com/naari3/otomad-feed/blob/main/osmosfeed.yaml)リストに既に追加されていないかご確認ください！
- type: checkboxes
  id: confirm
  attributes:
    label: 重複がないことを確認する
    options:
      - label: "[この](https://github.com/naari3/otomad-feed/blob/main/osmosfeed.yaml)リストにまだ追加されていないことを確認しました"
        required: true