name: Request for Additional blog
description: "Create a request to add a blog to the feed."
title: "[Add]: "
labels: ["add request"]

body:
- type: input
  id: blog-title
  attributes:
    label: "Blog title"
    placeholder: AWESOME BLOG
  validations:
    required: true
- type: input
  id: blog-url
  attributes:
    label: "Blog URL"
    placeholder: https://blog.example.com
  validations:
    required: true
- type: input
  id: blog-feed-url
  attributes:
    label: "Blog feed URL (if possible)"
    placeholder: https://blog.example.com/feed
- type: checkboxes
  id: confirm
  attributes:
    label: Make sure there are no duplicates [here](https://github.com/naari3/otomad-feed/blob/main/osmosfeed.yaml)
    options:
      - label: I've confirmed that there are no duplicates [here](https://github.com/naari3/otomad-feed/blob/main/osmosfeed.yaml).
        required: true