name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm i
      - run: npm run fix
      - name: suggest
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: feed-lint
